version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Adjust the Python version as needed
    steps:
      - checkout  # Check out the code

      # Set up the environment (in this case, it's Python, so install dependencies if any)
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip

      # Run the unit tests from the root but specify the relative path to TestTriangle.py
      - run:
          name: Run unit tests
          command: python -m unittest Hw-02a/TestTriangle.py

workflows:
  version: 2
  test:
    jobs:
      - test
