version: 2.1

jobs:
  test:
    docker:
      # Use a Python image
      - image: circleci/python:3.8  # You can change the Python version if needed
    steps:
      - checkout  # Check out the code

      # Set up the environment (in this case, it's Python, so install dependencies if any)
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip

      # Run the unit tests
      - run:
          name: Run unit tests
          command: python -m unittest TestTriangle.py

workflows:
  version: 2
  test:
    jobs:
      - test
