version: 2.1

jobs:
  test:
    docker:
      # Use a Python image
      - image: circleci/python:3.8  # Adjust the Python version as needed
    steps:
      - checkout  # Check out the code

      # Set up the environment (in this case, it's Python, so install dependencies if any)
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip

      # Change directory to where the Python files are located
      - run:
          name: Navigate to Hw-02a
          command: cd Hw-02a

      # Run the unit tests from the Hw-02a directory
      - run:
          name: Run unit tests
          command: python -m unittest TestTriangle.py

workflows:
  version: 2
  test:
    jobs:
      - test
